#!/bin/bash
# OpenClaw deploy.sh (OpenRouter variant) — provisions ONE ORB Cloud
# computer running an OpenClaw Gateway with OpenRouter as the LLM upstream,
# exposed at https://<id>.orbcloud.dev (port 18789).
#
# Hosted at https://orbcloud.dev/templates/openclaw-openrouter for
# curl-pipe-bash:
#
#     bash <(curl -fsSL https://orbcloud.dev/templates/openclaw-openrouter)
#
# Pick any model in OpenRouter's catalog by exporting OPENROUTER_MODEL
# (e.g. "anthropic/claude-sonnet-4.5", "openai/gpt-5", "google/gemini-2.5-pro").
# Leave it unset to use whatever default `openclaw onboard` writes for the
# openrouter provider.

set -e
set -u

TEMPLATE_BASE="${TEMPLATE_BASE:-https://raw.githubusercontent.com/AWLSEN/orb-templates/main/openclaw-openrouter}"

# Source shared helpers (orb_swarm_create, require_env, etc.)
LIB_TMP=$(mktemp -d)
trap 'rm -rf "$LIB_TMP"' EXIT
curl -fsSL https://raw.githubusercontent.com/AWLSEN/orb-templates/main/lib/deploy-common.sh -o "$LIB_TMP/lib.sh"
# shellcheck disable=SC1091
source "$LIB_TMP/lib.sh"

# ──────────────────────────────────────────────────────────────────────────────
# Inputs (env vars)
# ──────────────────────────────────────────────────────────────────────────────

require_env ORB_API_KEY OPENROUTER_API_KEY

# Optional model override. Empty by default — keeps openclaw onboard's
# wizard default if the user doesn't pick one explicitly.
OPENROUTER_MODEL="${OPENROUTER_MODEL:-}"

# Random 6-char suffix so successive deploys don't collide on org-unique name.
SUFFIX=$(tr -dc 'a-z0-9' </dev/urandom | head -c 6)
DEPLOY_NAME="${DEPLOY_NAME:-openclaw-or-${SUFFIX}}"

# ──────────────────────────────────────────────────────────────────────────────
# Render orb.toml from the template — fetch the .tpl, no substitutions needed
# (everything that varies is a ${VAR} secret reference resolved at deploy time
# by the cloud, not template-rendered).
# ──────────────────────────────────────────────────────────────────────────────

ORB_TOML=$(curl -fsSL "$TEMPLATE_BASE/orb.toml.tpl")

# Convert TOML → JSON for the API body (the runtime accepts JSON for orb_config).
TOML_AS_JSON=$(printf '%s' "$ORB_TOML" | python3 -c '
import json, sys
try:
    import tomllib
except ImportError:
    import tomli as tomllib
print(json.dumps(tomllib.loads(sys.stdin.read())))
')

# ──────────────────────────────────────────────────────────────────────────────
# Compose org_secrets — the runtime resolves ${VAR} in agent.env against this.
# OPENROUTER_MODEL is shipped through here too so start.sh can read it on
# first-run onboarding without making it a "required" secret.
# ──────────────────────────────────────────────────────────────────────────────

ORG_SECRETS=$(jq -n \
  --arg key "$OPENROUTER_API_KEY" \
  --arg model "$OPENROUTER_MODEL" \
  '{OPENROUTER_API_KEY: $key, OPENROUTER_MODEL: $model}')

# ──────────────────────────────────────────────────────────────────────────────
# Deploy.
# ──────────────────────────────────────────────────────────────────────────────

echo "→ deploy:    $DEPLOY_NAME"
if [ -n "$OPENROUTER_MODEL" ]; then
  echo "→ provider:  OpenRouter (model: $OPENROUTER_MODEL)"
else
  echo "→ provider:  OpenRouter (model: openclaw onboard default — set OPENROUTER_MODEL to override)"
fi
echo "→ resources: 2GB RAM, 8GB disk"
echo "→ exposes:   port 18789 (OpenClaw Gateway)"
echo

# Single-computer deploy via /v1/swarms with replicas=1. The swarm primitive
# already handles config-upload + build + secrets-persist + subdomain
# provisioning in one call; reusing it for "deploy one" is the simplest path.
RESPONSE=$(orb_swarm_create "$DEPLOY_NAME" 1 "$TOML_AS_JSON" "$ORG_SECRETS")

# Extract the single member's computer ID + subdomain URL.
SWARM_ID=$(echo "$RESPONSE" | jq -r '.swarm_id')
COMPUTER_ID=$(echo "$RESPONSE" | jq -r '.computers[0].id // empty')
SUBDOMAIN_URL=$(echo "$RESPONSE" | jq -r '"https://" + .computers[0].subdomain + "/"')

if [ -z "$COMPUTER_ID" ]; then
  echo "ERROR: deploy failed — no member returned." >&2
  echo "$RESPONSE" | jq . >&2 || echo "$RESPONSE" >&2
  exit 1
fi

# A short ID for the UX — first 8 chars of the UUID.
SHORT_ID=$(echo "$COMPUTER_ID" | cut -c1-8)

# Pull the gateway auth token off the computer so the user can hit the
# /v1/chat/completions endpoint we enable in start.sh. The token is
# generated by `openclaw onboard` and written to ~/.openclaw/openclaw.json
# at gateway.auth.token. The cloud's GET /v1/computers/{id}/files/{path}
# endpoint streams file bytes back. Poll up to 60s — onboard runs after
# the build phase, so the file may not exist immediately on first deploy.
GATEWAY_TOKEN=""
for attempt in 1 2 3 4 5 6; do
  GATEWAY_TOKEN=$(curl -sS --max-time 10 \
    -H "Authorization: Bearer $ORB_API_KEY" \
    "https://api.orbcloud.dev/v1/computers/$COMPUTER_ID/files/root/.openclaw/openclaw.json" \
    2>/dev/null \
    | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("gateway",{}).get("auth",{}).get("token",""))' \
    2>/dev/null) || true
  [ -n "$GATEWAY_TOKEN" ] && break
  sleep 10
done

cat <<DEPLOYED

✓ deployed.

  Gateway URL:  $SUBDOMAIN_URL
  Health:       ${SUBDOMAIN_URL}healthz
  Computer:     $COMPUTER_ID  (short: $SHORT_ID)

  Cold-start (first wake) takes ~30–60s while openclaw finishes onboarding
  and gateway plugins finish first-time install. Subsequent wakes are < 1s
  (CRIU restore from incremental checkpoint).

  → Open the Gateway UI:        $SUBDOMAIN_URL
  → Open the web terminal:      https://api.orbcloud.dev/terminal/$COMPUTER_ID?key=\$ORB_API_KEY
DEPLOYED

if [ -n "$GATEWAY_TOKEN" ]; then
  cat <<TOKENED
  → Gateway auth token:         $GATEWAY_TOKEN
                                (written by \`openclaw onboard\`; gates the
                                /v1/chat/completions endpoint we enable by
                                default)

  → Send a message via curl:
      curl -X POST ${SUBDOMAIN_URL}v1/chat/completions \\
        -H "Authorization: Bearer $GATEWAY_TOKEN" \\
        -H "content-type: application/json" \\
        -d '{"model":"openclaw","messages":[{"role":"user","content":"hello"}]}'

TOKENED
else
  cat <<UNTOKENED
  → Gateway auth token:         (not yet readable — agent still booting; rerun
                                this script's "Send a message via curl" block
                                in 30s, or fetch it from the web terminal at
                                /root/.openclaw/openclaw.json under
                                gateway.auth.token)

UNTOKENED
fi

cat <<TEARDOWN
  Tear down: curl -X DELETE -H "Authorization: Bearer \$ORB_API_KEY" \\
               https://api.orbcloud.dev/v1/swarms/$SWARM_ID

TEARDOWN
